name: Build and Deploy

on:
  push:
    branches:
      - main  # Cambiar por la rama principal de tu repositorio

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Transfer artifact to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}  # Si has configurado una frase de paso para la clave SSH
        source: "target/*.jar"
        target: "/home/dietpi/dietPiServer/java-app/ProyGestionDeTareas/"
